### ISSUE TITLE
Update returned data type for properties in token and addresses collections from string to number

### ISSUE THREAD

**Issue by cgcardona** [simpleledger/SLPDB#12]
Can we update the following to be numbers instead of strings? Thanks!

* tokenStats.qty_token_minted
* tokenStats.qty_token_burned
* tokenStats.qty_token_circulating_supply
* tokenDetails.genesisOrMintQuantity

## Tokens collection

Run this query

https://slpdb.bitcoin.com/explorer2/ewogICJ2IjogMywKICAicSI6IHsKICAgICJkYiI6IFsidCJdLAogICAgImZpbmQiOiB7fSwKICAgICJsaW1pdCI6IDEsCiAgICAicHJvamVjdCI6IHsKICAgICAgIl9pZCI6IDAsCiAgICAgICJ0b2tlblN0YXRzLnF0eV90b2tlbl9taW50ZWQiOiAgMSwKICAgICAgInRva2VuU3RhdHMucXR5X3Rva2VuX2J1cm5lZCI6ICAxLAogICAgICAidG9rZW5TdGF0cy5xdHlfdG9rZW5fY2lyY3VsYXRpbmdfc3VwcGx5IjogIDEsCiAgICAgICJ0b2tlbkRldGFpbHMuZ2VuZXNpc09yTWludFF1YW50aXR5IjogIDEKICAgIH0KICB9Cn0=

Note the output is strings.

```js
{  
   "t":[  
      {  
         "tokenDetails":{  
            "genesisOrMintQuantity":"1000"
         },
         "tokenStats":{  
            "qty_token_minted":"1000",
            "qty_token_burned":"0",
            "qty_token_circulating_supply":"1000"
         }
      }
   ]
```

## Addresses collection

Run this query

https://slpdb.bitcoin.com/explorer2/ewogICJ2IjogMywKICAicSI6IHsKICAgICJkYiI6IFsiYSJdLAogICAgImZpbmQiOiB7CiAgICAgICJ0b2tlbkRldGFpbHMudG9rZW5JZEhleCI6ICI1MjdhMzM3ZjM0ZTA0YjE5NzRjYjhhMWVkYzdjYTMwYjJlNDQ0YmVhMTExYWZjMTIyMjU5NTUyMjQzYzFkYmUzIiwKICAgICAgInRva2VuX2JhbGFuY2UiOiB7ICIkZ3RlIjogMCAgfQogICAgfSwKICAgICJsaW1pdCI6IDEwMDAwLAogICAgInByb2plY3QiOiB7ICJ0b2tlbl9iYWxhbmNlIjogMSwgIl9pZCI6IDAgfQogIH0sCiAgInIiOiB7ICAgIAogICAgImYiOiAiWy5bXSB8IHsgYmFsYW5jZTogLnRva2VuX2JhbGFuY2UgfV0iCiAgfQp9

Returned data

```js
[
  {   "balance": "800000" },
  {   "balance": "1" }
  ...
]
```

**Comment by jcramer** [comment]
Since JS is limited in precision for `number` type (its 53-bits I think) we've gone this route of the presentation the query result as a `string` since theoretically the first three properties you list can be larger than a 64-bit number.  

Here is what we're doing:

- In SLPDB these properties are handled as a `BigNumber` type to allow greater than 64-bit numbers, and 
- In MongoDB these properties are handled as `Decimal128` type for the same reason.  The values are stored as `Decimal128` type in the DB you can work with them as numbers in your queries (e.g., you can use `"$gte"` operator, etc).  
- Before the query result is returned to you, slpqueryd converts the `Decimal128` type to a `string` type automatically. See slpqueryd the conversion code [here](https://github.com/fountainhead-cash/slpqueryd/blob/9deba8af78f2bd871de58423b75f246d1eab7d3a/index.js#L145).  

Having `string` returned in the query allows us to present to you an accurate number without having this sort of ugly `Decimal128` object to handle.  Our intention was that if a query result consumer would like to do math with these values they should first convert the string result to a `BigNumber` or `Decimal128` type using the string interface available for those types.

Is this helpful or does this approach cause issues?

**Comment by jcramer** [comment]
I'm going to close this issue as I'm assuming that all that was needed here was clarification, see the update to the readme above.   

Feel free to re-open if necessary.
